from stjames import Molecule

import rowan

# Set your API key or use the ROWAN_API_KEY environment variable
# rowan.api_key = "rowan-sk..."
folder = rowan.get_folder("examples")

# ordinarily, we'd try a 3D conformer and see what the strain is.
# here we'll investigate the strain of the autogenerated hexane conformer
workflow = rowan.submit_strain_workflow(
    initial_molecule=Molecule.from_smiles("CCCCCC"),
    name="test autogen hexane strain",
    folder=folder,
)

print(f"View workflow privately at: https://labs.rowansci.com/strain/{workflow.uuid}")
result = workflow.result()
print(result)
# e.g. <StrainResult strain=2.34 kcal/mol>
